### ISSUE TITLE
 Cannot read property 'includes' of undefined when disableWhenValid = false

### ISSUE THREAD

**Issue by francescocaveglia** [elisherer/webpack-dev-server-waitpage#23]
I have the disableWhenValid:false option and, sometime I get this error
```node
(node:23364) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at C:\GIT\myproject\node_modules\webpack-dev-server-waitpage\lib\index.js:75:52
    at Layer.handle [as handle_request] (C:\GIT\myproject\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\GIT\myproject\node_modules\express\lib\router\index.js:317:13)
    at C:\GIT\myproject\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\GIT\myproject\node_modules\express\lib\router\index.js:335:12)    at next (C:\GIT\myproject\node_modules\express\lib\router\index.js:275:10)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:127:14)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:131:14)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:131:14)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:131:14)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:131:14)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:131:14)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:131:14)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:131:14)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:131:14)
    at next (C:\GIT\myproject\node_modules\express\lib\router\route.js:131:14)
(node:23364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3874)
```

not sure which calls are causing the problem but probably a null check on `req.headers.accept` could solve:
https://github.com/elisherer/webpack-dev-server-waitpage/blob/c028d9fe7d0ed712d3a75af2c7e7b37f0854f329/lib/index.js#L75

anyway the error doesn't break the compilation, only the wait page.

Thanks

**Comment by elisherer** [comment]
Added validation suggested to [2.1.1](https://github.com/elisherer/webpack-dev-server-waitpage/releases/tag/2.1.1)
